title: wtfisthisweeksuberforcats

#ga_tag: UA-1974-1

github_corner:
  url: http://github.com/pikesley/wtfisthisweeksuberforcats
  colour: '#fa8100'

homepage:
  name: sam
  url: http://sam.pikesley.org

bootswatch: flatly
